version: 5.8.0.{build} # Only change for mayor versions (e.g. 6.0.0)
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true 
  matrix:
  - job_name: windows
    appveyor_build_worker_image: Visual Studio 2022
  - job_name: linux
    appveyor_build_worker_image: Ubuntu
matrix:
  fast_finish: true
only_commits:
  files:
    - appveyor.yml
    - Src/**/*

for:
  -
    matrix:
      only:
        - job_name: windows
    init:
      # default is: core.autocrlf input
      - git config --global core.autocrlf true
    build_script:
      - ps: cd $env:APPVEYOR_BUILD_FOLDER\Src
      - ps: dotnet --version
      - ps: dotnet restore --verbosity quiet
      - ps: dotnet add .\MailMergeLib.Tests\MailMergeLib.Tests.csproj package AltCover
      - ps: |
          $version = "5.8.2"
          $versionFile = $version + "." + ${env:APPVEYOR_BUILD_NUMBER}

          if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
              $version = $version + "-PR" + $env:APPVEYOR_PULL_REQUEST_NUMBER
          }
          dotnet build MailMergeLib.sln /verbosity:minimal /t:rebuild /p:configuration=release /p:IncludeSymbols=true /p:ContinuousIntegrationBuild=true /p:Version=$version /p:FileVersion=$versionFile /nowarn:CS1591,CS0618
          dotnet pack MailMergeLib.sln --verbosity minimal --no-build --configuration release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=$env:APPVEYOR_BUILD_FOLDER/artifacts /p:ContinuousIntegrationBuild=true
    test_script:
      - cmd: nuget install Appveyor.TestLogger
      - cmd: dotnet test --no-build --framework net6.0 --test-adapter-path:. --logger:Appveyor MailMergeLib.sln /p:configuration=release /p:AltCover=true /p:AltCoverXmlReport="coverage.xml" /p:AltCover=true /p:AltCoverStrongNameKey="..\MailMergeLib\MailMergeLib.snk" /p:AltCoverAssemblyExcludeFilter="MailMergeLib.Tests|NUnit3.TestAdapter" /p:AltCoverLineCover="true"
      - cmd: nuget install codecov -excludeversion
      - cmd: .\Codecov\Tools\win7-x86\codecov.exe -f ".\MailMergeLib.Tests\coverage.net6.0.xml" -n net6.0win
    artifacts:
      - path: 'artifacts\*.nupkg'
        type: NuGetPackage
      - path: 'artifacts\*.snupkg'
        type: NuGetPackage
    deploy:
      - provider: NuGet
        api_key:
          secure: siTK+zMCX6XYTT2G7uhX9XjB6LNhDtZheum/MKIfrnsBITjZ+yEGAPNKVL/LCEPB
        on:
          branch: main
  -
    matrix:
      only:
        - job_name: linux
    build_script:
      - cd $APPVEYOR_BUILD_FOLDER/Src
      - dotnet --version
      - dotnet restore --verbosity quiet
      - dotnet add ./MailMergeLib.Tests/MailMergeLib.Tests.csproj package AltCover
      - dotnet build MailMergeLib.sln /verbosity:minimal /t:rebuild /p:configuration=release /nowarn:CS1591,CS0618 
    test_script:
      - dotnet test --no-build --framework net6.0 MailMergeLib.sln /p:configuration=release /p:AltCover=true /p:AltCoverXmlReport="coverage.xml" /p:AltCover=true /p:AltCoverStrongNameKey="../MailMergeLib/MailMergeLib.snk" /p:AltCoverAssemblyExcludeFilter="MailMergeLib.Tests|NUnit3.TestAdapter" /p:AltCoverLineCover="true"
      - bash <(curl -s https://codecov.io/bash) -f ./MailMergeLib.Tests/coverage.net6.0.xml -n net6.0linux
